apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure-app
  template:
    metadata:
      labels:
        app: insecure-app
    spec:
      containers:
        - name: no-security
          image: nginx:latest
          resources:
            requests:
              cpu: "100m"
          env:
            - name: API_KEY
              value: "supersecretapikey"
          securityContext:
            privileged: true
      hostNetwork: true
      volumes:
        - name: insecure-volume
          hostPath:
            path: /etc
